### ISSUE TITLE
Going open-source: todo list 

### ISSUE THREAD

**Issue by danglotb** [davidson-consulting/diff-jjoules#5]
The following tasks should be addressed in order to endure a minimal quality.

- [x] Continuous Integration
- [x] SonarCloud Scan
- [x] Checkstyle
- [ ] ~~Licence Check~~ **EDIT** Won't do this since the Licence is not mandatory in each file.
- [x] Codecov
- [ ] ~~Lighthouse Audit~~ **EDIT** Won't do this since it is for web apps and web pages.
- [x] Dependabot
- [x] `README.md`
- [x] Badges in `README.md`
- [x] `CONTRIBUTING.md`
- [X] License GNU GPL
